version: '3.3'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: db
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: